# Generated by Django 5.2.1 on 2025-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
