# Generated by Django 5.2.1 on 2025-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_room', '0002_puzzle_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
