# Generated by Django 5.2.1 on 2025-06-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_room', '0004_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='solution',
            new_name='answer',
        ),
    ]
