# Generated by Django 5.2.1 on 2025-06-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escape_room', '0005_rename_solution_puzzle_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='difficulty',
        ),
    ]
